class AppAssets {
  static String icBody = "assets/icons/ic_body.png",
icEar = "assets/icons/ic_ear.png",
icEye = "assets/icons/ic_eye.png",
icHeart = "assets/icons/ic_heart.png",
ickidney = "assets/icons/ic_kidney.png",
icLiver = "assets/icons/ic_liver.png",
icLungs = "assets/icons/ic_lungs.png",
icStomach = "assets/icons/ic_stomach.png",
icTooth = "assets/icons/ic_tooth.png",
imgLogin= "assets/images/img_login.png",
imgSignup = "assets/images/img_signup.png",
imgWelcome = "assets/images/img_welcome.png",
imgDoc1 = "assets/images/img_doc1.jpg",
imgDoc2 = "assets/images/img_doc2.jpg",
imgDoc4 = "assets/images/img_doc4.png",
imgDoc3 = "assets/images/img_doc3.jpg",
imgDoc5 = "assets/images/img_doc5.png",
imgDoc6 = "assets/images/img_doc6.png",
imgDoc7 = "assets/images/img_doc7.webp",
imgDoc8 = "assets/images/img_doc8.png",
imgDoc9 = "assets/images/img_doc9.png",
imgDoc10 = "assets/images/img_doc10.png";
}